### ISSUE TITLE
Commands send from the Printer Control Terminal Double Wrapped Array

### ISSUE THREAD

**Issue by MTrab** [OctoFarm/OctoFarm#240]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**
When sending a command from Octofarm, it looks like the string is formattet in some strange way, resulting in Octoprint responding with an error

**To Reproduce**
1. Go to 'Printer'
2. Write G or M command in text field
3. Press send

**Expected behavior**
M or G codes being sent correctly, as entered in the text field.

**Screenshots**
![image](https://user-images.githubusercontent.com/14296463/106314233-b6a09f00-6269-11eb-9d94-8f0bfedea8a4.png)

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13] 12.16.3-0017
 - OctoFarm Version [e.g. 1.5.5.7] 1.1.9-dev5
 - OctoPrint Version [e.g. 1.4.1] 1.5.3
 - OctoPrint Plugins [e.g. bed visualiser, octoklipper, printtimegenius] Enclosure Plugin

**Additional context**

**Comment by NotExpectedYet** [comment]
Could you screenshot the console output please? Think something else is going on here as I can't reproduce with your command.

![image](https://user-images.githubusercontent.com/61137988/106347455-90edb700-62b6-11eb-8008-31c207764bf9.png)

**Comment by MTrab** [comment]
Console gives absolutely no output on this

**Comment by NotExpectedYet** [comment]
I'll need to repro to figure it out as it's client side and that's all compiled for the user. 

When typing in the command for me it sends fine, even with mutli-lined sends. Same for enter fire, and Button press fire.

**Comment by MTrab** [comment]
Issue is the same in all browser and on both printers.
Just a tought - could this be some kind of language interpretation?
My system language is Danish, so is my input locale.

**Comment by NotExpectedYet** [comment]
> Issue is the same in all browser and on both printers.
> Just a tought - could this be some kind of language interpretation?
> My system language is Danish, so is my input locale.

That's a good thought. I gather nothing comes up in the console when you send it apart from the octoprint error? 

I will have a search and see if there's any issues with language parsing from an input. If that is the case it's probably my new line interpretation or that's my guess. 

I presumed it would be fine now a days. I'll put some more console outputs in a push tomorrow for you to try if you'd have time? 

Just trying to cover all basis for now, not sure which one of the above would be most fruitful.

**Comment by NotExpectedYet** [comment]
What's confusing is theres that little u before the array quotes which I've never seen before.

**Comment by MTrab** [comment]
I'll fire up my work laptop later today, it's with EN-US localization - the we can see if that makes a difference.

**Comment by NotExpectedYet** [comment]
It's all sent and managed client side yet so fingers crossed. I'll see about putting some UTF-8 encoding on the field should resolve it.

**Comment by MTrab** [comment]
Nope - still doesn't work on the laptop.
But now the terminal windows actually are not showing anything anymore :/

I can see on the Octoprint terminal pane that the error are the same.

**Comment by NotExpectedYet** [comment]
It's something else then. I wonder if it's related to the profile bug. Could you fire me through your state and API logs please?

**Comment by MTrab** [comment]
[OctoFarm-API (1).log](https://github.com/NotExpectedYet/OctoFarm/files/5920244/OctoFarm-API.1.log)
[OctoFarm-State5.log](https://github.com/NotExpectedYet/OctoFarm/files/5920247/OctoFarm-State5.log)

**Comment by MTrab** [comment]
Unfortunately still an issue :(

From console
[192.168.1.9-1612643408065.log](https://github.com/NotExpectedYet/OctoFarm/files/5937590/192.168.1.9-1612643408065.log)

**Comment by NotExpectedYet** [comment]
Well this one's a PIA, even worse the array is there formatted perfect in the error output :/

**Comment by NotExpectedYet** [comment]
Right so I've double checked everything on this side of things, the function, the log... it for all intensive purposes is sending the correct array, and that's even outputted in your log you sent. I see the individual key press G, 2, 8 and then the array created on the input ["G28"]. 

I put another set of logging in to see what's getting fired. 

![image](https://user-images.githubusercontent.com/61137988/107845654-05efdf00-6dd5-11eb-9417-c053e9e7acac.png)

You should have something like the above.

If that is showing correctly, then I'd say this was something to do with OctoPrint specifically.

**Comment by MTrab** [comment]
This is what I see in 1.1.11-dev12

![image](https://user-images.githubusercontent.com/14296463/108622717-f60e7580-743a-11eb-8778-3c88666243e5.png)

**Comment by NotExpectedYet** [comment]
I've found a bug, somehow that Array is getting double quoted before sending but I can't understand why that is only not working on your system. 

I'll update the title to reflect this and have a look.
