### ISSUE TITLE
System Page doesn't load due to failing to check for git repository 

### ISSUE THREAD

**Issue by e1miran** [OctoFarm/OctoFarm#962]
### OctoFarm Version

1.2

### OctoPrint Version(s)

1.80

### pm2 or docker?

docker

### Operating System

Debian

### Location of the problem

Web Interface

### Description of the problem

```markdown
I'm having the issue with failing to acquire user list as described here: https://github.com/OctoFarm/OctoFarm/issues/912. However, I cannot access the System tab in order to increase the timeout. Clicking on the System link just tries to load the page indefinitely.
```

### Steps taken to reproduce

Clicked on System link

### What did you expect to happen

Open System page

### To avoid the problem I had to

No workaround

**Comment by NotExpectedYet** [comment]
> ### OctoFarm Version
> 
> 1.2
> ### OctoPrint Version(s)
> 
> 1.80
> ### pm2 or docker?
> 
> docker
> ### Operating System
> 
> Debian
> ### OctoPrint Plugins
> 
> _No response_
> ### Location of the problem
> 
> Web Interface
> ### Description of the problem
> 
> ```gfm
> I'm having the issue with failing to acquire user list as described here: https://github.com/OctoFarm/OctoFarm/issues/912. However, I cannot access the System tab in order to increase the timeout. Clicking on the System link just tries to load the page indefinitely.
> ```
> 
> ### Steps taken to reproduce
> 
> Clicked on System link
> ### What did you expect to happen
> 
> Open System page
> ### To avoid the problem I had to
> 
> No workaround
Cheers for the report will sort it. It's because there's 0 printers for some reason.

**Comment by NotExpectedYet** [comment]
Alternatively you could try access your database with mongo compass and edit it there. I should have it sorted for tomorrow though.

**Comment by e1miran** [comment]
Thank you. Just an update. I managed to increase the timeout using mongo shell. This allowed the printers to connect successfully and I was able to configure them. They appear as online and operational. However, System Page still does not load.

![Screen Shot 2022-05-20 at 2 29 44 PM](https://user-images.githubusercontent.com/41588119/169590737-8acaab55-84d3-47f0-b173-05e37bc5dd0e.png)

**Comment by NotExpectedYet** [comment]
Do you have access to the logs folder at all? It's not what I originally thought. 

I'll setup a new install in the morning to double check what's going on as well like.

**Comment by e1miran** [comment]
I'll check. Do you know where it's located on a Docker install?

**Comment by NotExpectedYet** [comment]
Should be /data/logs if monolithic or app/logs if normal I think.

**Comment by e1miran** [comment]
Which of the logs do you need to see?

**Comment by NotExpectedYet** [comment]
pm2.error.log would be best start as that should show anything I didn't catch.

**Comment by e1miran** [comment]
This appears to be from the last restart. I did attempt the the System page after restart.

`2022-05-20T13:48:42: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T13:48:42: 
2022-05-20T13:48:42:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T13:48:42:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T13:48:42:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T13:48:42:     at new Promise (<anonymous>)
2022-05-20T13:48:42:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T13:48:42:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T13:48:42:     at Generator.next (<anonymous>)
2022-05-20T13:48:42:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T13:48:42:   task: {
2022-05-20T13:48:42:     format: 'utf-8',
2022-05-20T13:48:42:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T13:48:42:     parser: [Function: parser]
2022-05-20T13:48:42:   }
2022-05-20T13:48:42: }
2022-05-20T13:52:20: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T13:52:20: 
2022-05-20T13:52:20:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T13:52:20:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T13:52:20:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T13:52:20:     at new Promise (<anonymous>)
2022-05-20T13:52:20:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T13:52:20:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T13:52:20:     at Generator.next (<anonymous>)
2022-05-20T13:52:20:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T13:52:20:   task: {
2022-05-20T13:52:20:     format: 'utf-8',
2022-05-20T13:52:20:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T13:52:20:     parser: [Function: parser]
2022-05-20T13:52:20:   }
2022-05-20T13:52:20: }
2022-05-20T13:56:07: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T13:56:07: 
2022-05-20T13:56:07:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T13:56:07:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T13:56:07:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T13:56:07:     at new Promise (<anonymous>)
2022-05-20T13:56:07:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T13:56:07:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T13:56:07:     at Generator.next (<anonymous>)
2022-05-20T13:56:07:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T13:56:07:   task: {
2022-05-20T13:56:07:     format: 'utf-8',
2022-05-20T13:56:07:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T13:56:07:     parser: [Function: parser]
2022-05-20T13:56:07:   }
2022-05-20T13:56:07: }
2022-05-20T13:56:45: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T13:56:45: 
2022-05-20T13:56:45:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T13:56:45:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T13:56:45:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T13:56:45:     at new Promise (<anonymous>)
2022-05-20T13:56:45:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T13:56:45:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T13:56:45:     at Generator.next (<anonymous>)
2022-05-20T13:56:45:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T13:56:45:   task: {
2022-05-20T13:56:45:     format: 'utf-8',
2022-05-20T13:56:45:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T13:56:45:     parser: [Function: parser]
2022-05-20T13:56:45:   }
2022-05-20T13:56:45: }
2022-05-20T13:59:54: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T13:59:54: 
2022-05-20T13:59:54:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T13:59:54:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T13:59:54:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T13:59:54:     at new Promise (<anonymous>)
2022-05-20T13:59:54:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T13:59:54:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T13:59:54:     at Generator.next (<anonymous>)
2022-05-20T13:59:54:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T13:59:54:   task: {
2022-05-20T13:59:54:     format: 'utf-8',
2022-05-20T13:59:54:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T13:59:54:     parser: [Function: parser]
2022-05-20T13:59:54:   }
2022-05-20T13:59:54: }
2022-05-20T14:00:14: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:00:14: 
2022-05-20T14:00:14:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:00:14:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:00:14:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:00:14:     at new Promise (<anonymous>)
2022-05-20T14:00:14:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:00:14:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:00:14:     at Generator.next (<anonymous>)
2022-05-20T14:00:14:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:00:14:   task: {
2022-05-20T14:00:14:     format: 'utf-8',
2022-05-20T14:00:14:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:00:14:     parser: [Function: parser]
2022-05-20T14:00:14:   }
2022-05-20T14:00:14: }
2022-05-20T14:10:12: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:10:12: 
2022-05-20T14:10:12:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:10:12:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:10:12:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:10:12:     at new Promise (<anonymous>)
2022-05-20T14:10:12:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:10:12:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:10:12:     at Generator.next (<anonymous>)
2022-05-20T14:10:12:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24)
2022-05-20T14:10:12:     at runMicrotasks (<anonymous>)
2022-05-20T14:10:12:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
2022-05-20T14:10:12:   task: {
2022-05-20T14:10:12:     format: 'utf-8',
2022-05-20T14:10:12:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:10:12:     parser: [Function: parser]
2022-05-20T14:10:12:   }
2022-05-20T14:10:12: }
2022-05-20T14:11:23: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:11:23: 
2022-05-20T14:11:23:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:11:23:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:11:23:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:11:23:     at new Promise (<anonymous>)
2022-05-20T14:11:23:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:11:23:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:11:23:     at Generator.next (<anonymous>)
2022-05-20T14:11:23:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:11:23:   task: {
2022-05-20T14:11:23:     format: 'utf-8',
2022-05-20T14:11:23:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:11:23:     parser: [Function: parser]
2022-05-20T14:11:23:   }
2022-05-20T14:11:23: }
2022-05-20T14:15:01: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:15:01: 
2022-05-20T14:15:01:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:15:01:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:15:01:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:15:01:     at new Promise (<anonymous>)
2022-05-20T14:15:01:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:15:01:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:15:01:     at Generator.next (<anonymous>)
2022-05-20T14:15:01:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24)
2022-05-20T14:15:01:     at runMicrotasks (<anonymous>)
2022-05-20T14:15:01:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
2022-05-20T14:15:01:   task: {
2022-05-20T14:15:01:     format: 'utf-8',
2022-05-20T14:15:01:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:15:01:     parser: [Function: parser]
2022-05-20T14:15:01:   }
2022-05-20T14:15:01: }
2022-05-20T14:17:03: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:17:03: 
2022-05-20T14:17:03:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:17:03:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:17:03:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:17:03:     at new Promise (<anonymous>)
2022-05-20T14:17:03:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:17:03:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:17:03:     at Generator.next (<anonymous>)
2022-05-20T14:17:03:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:17:03:   task: {
2022-05-20T14:17:03:     format: 'utf-8',
2022-05-20T14:17:03:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:17:03:     parser: [Function: parser]
2022-05-20T14:17:03:   }
2022-05-20T14:17:03: }
2022-05-20T14:28:21: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:28:21: 
2022-05-20T14:28:21:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:28:21:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:28:21:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:28:21:     at new Promise (<anonymous>)
2022-05-20T14:28:21:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:28:21:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:28:21:     at Generator.next (<anonymous>)
2022-05-20T14:28:21:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:28:21:   task: {
2022-05-20T14:28:21:     format: 'utf-8',
2022-05-20T14:28:21:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:28:21:     parser: [Function: parser]
2022-05-20T14:28:21:   }
2022-05-20T14:28:21: }
2022-05-20T14:31:00: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:31:00: 
2022-05-20T14:31:00:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:31:00:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:31:00:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:31:00:     at new Promise (<anonymous>)
2022-05-20T14:31:00:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:31:00:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:31:00:     at Generator.next (<anonymous>)
2022-05-20T14:31:00:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:31:00:   task: {
2022-05-20T14:31:00:     format: 'utf-8',
2022-05-20T14:31:00:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:31:00:     parser: [Function: parser]
2022-05-20T14:31:00:   }
2022-05-20T14:31:00: }
2022-05-20T14:45:07: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:45:07: 
2022-05-20T14:45:07:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:45:07:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:45:07:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:45:07:     at new Promise (<anonymous>)
2022-05-20T14:45:07:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:45:07:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:45:07:     at Generator.next (<anonymous>)
2022-05-20T14:45:07:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:45:07:   task: {
2022-05-20T14:45:07:     format: 'utf-8',
2022-05-20T14:45:07:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:45:07:     parser: [Function: parser]
2022-05-20T14:45:07:   }
2022-05-20T14:45:07: }
2022-05-20T14:50:20: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:50:20: 
2022-05-20T14:50:20:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:50:20:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:50:20:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:50:20:     at new Promise (<anonymous>)
2022-05-20T14:50:20:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:50:20:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:50:20:     at Generator.next (<anonymous>)
2022-05-20T14:50:20:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:50:20:   task: {
2022-05-20T14:50:20:     format: 'utf-8',
2022-05-20T14:50:20:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:50:20:     parser: [Function: parser]
2022-05-20T14:50:20:   }
2022-05-20T14:50:20: }
2022-05-20T14:50:30: GitError: fatal: Not a git repository (or any of the parent directories): .git
2022-05-20T14:50:30: 
2022-05-20T14:50:30:     at Object.action (/app/server/node_modules/simple-git/dist/cjs/index.js:1194:25)
2022-05-20T14:50:30:     at PluginStore.exec (/app/server/node_modules/simple-git/dist/cjs/index.js:1229:29)
2022-05-20T14:50:30:     at /app/server/node_modules/simple-git/dist/cjs/index.js:1590:43
2022-05-20T14:50:30:     at new Promise (<anonymous>)
2022-05-20T14:50:30:     at GitExecutorChain.handleTaskData (/app/server/node_modules/simple-git/dist/cjs/index.js:1588:16)
2022-05-20T14:50:30:     at GitExecutorChain.<anonymous> (/app/server/node_modules/simple-git/dist/cjs/index.js:1572:44)
2022-05-20T14:50:30:     at Generator.next (<anonymous>)
2022-05-20T14:50:30:     at fulfilled (/app/server/node_modules/simple-git/dist/cjs/index.js:55:24) {
2022-05-20T14:50:30:   task: {
2022-05-20T14:50:30:     format: 'utf-8',
2022-05-20T14:50:30:     commands: [ 'branch', '-v', '-a' ],
2022-05-20T14:50:30:     parser: [Function: parser]
2022-05-20T14:50:30:   }
2022-05-20T14:50:30: }`

**Comment by NotExpectedYet** [comment]
Hmm one of the tasks cheers for that. Gives me something to go on. The system page will be failing due to that I reckon.

**Comment by e1miran** [comment]
I managed to get a full log dump from Portainer and attach it here.

[_octofarm_logs.txt](https://github.com/OctoFarm/OctoFarm/files/8743478/_octofarm_logs.txt)

**Comment by NotExpectedYet** [comment]
> I managed to get a full log dump from Portainer and attach it here.
> 
> [_octofarm_logs.txt](https://github.com/OctoFarm/OctoFarm/files/8743478/_octofarm_logs.txt)

Brilliant thank you! 

Could you do me a favour and check the connection log on printer manage please? I'd like to know the response time your /api/user endpoint is returning in. I'm going to increase the default so other users don't run into the same user issue.

**Comment by NotExpectedYet** [comment]
Settings as well actually as that was failing to grab initially even at 5 seconds by the looks. Seems I underestimated those response times a lot!

**Comment by e1miran** [comment]
These are just the UI logs from the menu on the Manage button?

**Comment by e1miran** [comment]
Not sure which logs you mean. Maybe this will help??

![Screen Shot 2022-05-20 at 3 28 18 PM](https://user-images.githubusercontent.com/41588119/169598373-f0d8b333-4351-49a8-b3cb-92545993175f.png)

**Comment by NotExpectedYet** [comment]
It's on the top bar called "Connection Overview" sorry. If you expand a printer it will show you some endpoint URLs like /API/users and a milliseconds time next to it. I believe 10 seconds should be safe bet but just want to confirm.

**Comment by NotExpectedYet** [comment]
Ledge! Thanks, perfect.

**Comment by e1miran** [comment]
I'm using Rpi Zero 2's. Maybe they respond a bit slower.

**Comment by NotExpectedYet** [comment]
Dead on 5s huh, I'll go safer for the defaults to cover different setups. Thanks again, should have the system page fixed tomorrow morning GMT.

**Comment by e1miran** [comment]
You are the man! A steak is in order.

**Comment by NotExpectedYet** [comment]
Could be the case yeah, the settings endpoint is rather intensive at times.

**Comment by e1miran** [comment]
I had increased it the timeout to 5s, and it was doing well. But then I had problems again and raised it to 10s.

**Comment by NotExpectedYet** [comment]
I'm going to add a specific timeout for those two endpoints as it seems they are the problematic ones. Then the other settings don't need to be touched. 

It should only affect adding the printers though.

**Comment by NotExpectedYet** [comment]
I'll dig through your logs properly in the morning anyway and see if there's anything else I've missed :) helps loads so thanks again.

**Comment by e1miran** [comment]
Sure thing.

**Comment by NotExpectedYet** [comment]
Both the issues you reported should be now fixed with the latest update

**Comment by rogodra** [comment]
In my case, the problem persists with version 1.21, there is no way to enter System.

**Comment by NotExpectedYet** [comment]
Please post more logs because I confirmed myself this morning the other issue had gone so there is likely something else. 

If it doesn't docker as well it needs a new ticket opening please.

**Comment by e1miran** [comment]
The issue still persists with me (OP), as well. I've attached my latest logs below.

On a related note, I appear to have successfully updated and  run the latest version because [my other issue regarding iframes](https://github.com/OctoFarm/OctoFarm/issues/965) has been resolved. However, maybe a version indicator would be beneficial in the header or footer of the dashboard page since it's only in the System page.


[_octofarm_logs (1).txt](https://github.com/OctoFarm/OctoFarm/files/8747941/_octofarm_logs.1.txt)

**Comment by NotExpectedYet** [comment]
> The issue still persists with me (OP), as well. I've attached my latest logs below.
> 
> On a related note, I appear to have successfully updated and run the latest version because [my other issue regarding iframes](https://github.com/OctoFarm/OctoFarm/issues/965) has been resolved. However, maybe a version indicator would be beneficial in the header or footer of the dashboard page since it's only in the System page.

Yeah there is one but it only displays on development versions currently. I'll enable it for any version as it is handy as you say. 

Looking at the logs it's the same error, let me check what's going on and get back to you both

**Comment by NotExpectedYet** [comment]
Wow... sorry coding whilst tired this morning I seem to have never pushed the actual fix I made -_- will do a 1.2.2 now shortly and move the version to the top bar as well.

**Comment by NotExpectedYet** [comment]
Done! Will build the images now and do a release when they're done so when this closes your safe to pull

![image](https://user-images.githubusercontent.com/61137988/169661424-4a931886-0620-4bda-b116-c752632338ba.png)

**Comment by e1miran** [comment]
> Wow... sorry coding whilst tired this morning I seem to have never pushed the actual fix I made -_- will do a 1.2.2 now shortly and move the version to the top bar as well.

I had figured as much. I do some coding and have had this happen as well.

**Comment by NotExpectedYet** [comment]
> > Wow... sorry coding whilst tired this morning I seem to have never pushed the actual fix I made -_- will do a 1.2.2 now shortly and move the version to the top bar as well.
> 
> I had figured as much. I do some coding and have had this happen as well.

Easily done sometimes. Didn't pay attention to which branch I was on. 

Should be all live now :) I'll leave this open until confirmed.

**Comment by e1miran** [comment]
SUCCESS! System page is accessible and version numbering indicator appears on the header bar. Thanks.

**Comment by NotExpectedYet** [comment]
Welcome! 

Thanks for updating

**Comment by rogodra** [comment]
This latest version fixes the problem. Thanks!

**Comment by NotExpectedYet** [comment]
Most welcome :)
